### ISSUE TITLE
我看作者你可以更新think-orm，能否更新framework

### ISSUE THREAD

**Issue by hulang** [yzh52521/thinkphp-filesystem-cloud#1]
https://github.com/top-think/framework
把top-think/framework的composer.json
        "league/flysystem": "^1.1.4",
        "league/flysystem-cached-adapter": "^1.0",

更新到v2啊。。。
https://github.com/top-think/framework/issues/2638

**Comment by yuanzhihai** [comment]
我这个是 依赖think的flysystem的  think更新了 我就可以更新

**Comment by hulang** [comment]
@yzh52521 我的意思是你可以更新think，把think里面league/flysystem的扩展更新到v2。目前使用的还是v1。。很多包已经使用v2了。

**Comment by hulang** [comment]
@yzh52521 就不再建立一个：issues了。。你发布下版本啊，更新：sftp后，README.md文件里面，支持是：sfpt
我安装：composer require yzh52521/thinkphp-filesystem-cloud  报错

Using version ^1.0 for yzh52521/thinkphp-filesystem-cloud
./composer.json has been updated
Running composer update yzh52521/thinkphp-filesystem-cloud
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yzh52521/thinkphp-filesystem-cloud ^1.0 -> satisfiable by yzh52521/thinkphp-filesystem-cloud[1.0.0].
    - yzh52521/thinkphp-filesystem-cloud 1.0.0 requires overtrue/flysystem-qiniu ^1.10 -> found overtrue/flysystem-qiniu[1.x-dev] but it does not match your minimum-stability. 

You can also try re-running composer require with an explicit version constraint, e.g. "composer require yzh52521/thinkphp-filesystem-cloud:*" to figure out if any version is installable, or "composer require yzh52521/thinkphp-filesystem-cloud:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by hulang** [comment]
@yzh52521 就不再建立一个：issues了
在config/filesystem.php 配置了sftp的参数，上传到的是本地，我晕额，我使用原生sftp上传木有问题。
另外，sftp配置这里少个URL参数。就向：aliyun，qiniu 有个URL，我看了下你写的driver下面的所有文件，就sftp木有额。。
比如sftp上传后返回：/static/image/upload/20220706/bc301c2fccb3ba0289201d564bef8a10.png
我得有个域名对应啊。。https://github.com/static/image/upload/20220706/bc301c2fccb3ba0289201d564bef8a10.png

**Comment by hulang** [comment]
@yzh52521 你更新后，记得发布下版本啊

**Comment by hulang** [comment]
![QQ截图20220706173113](https://user-images.githubusercontent.com/4961831/177519170-df29849b-7487-418e-961c-74eeb6df3484.png)
写错了。
